### ISSUE TITLE
Add option to auto open info window on single map

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-google-maps#10]

**Comment by saltymouse** [comment]
This is also a feature I'd like but can't figure out how to implement myself. Perhaps instead of the info-window, there can be an option to set the MarkerWithLabel as seen here:

http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/docs/examples.html

Or, perhaps, is this already possible?

( Came here via https://wordpress.org/support/topic/market-box-not-showing-on-page-load )

**Comment by remcotolsma** [comment]
We currently have no plans to further expand this plugin.
